### PR TITLE
Restrict to aeson 2.0 or better

### PR DESCRIPTION
**Pull request by kayvank**
This PR is response to Slack conversation on [#cardano-dev channel](https://input-output-rnd.slack.com/archives/CCZSDE005/p1679613693027109) in regards to upgrading aeson to 2.0 or better.
Note that plutus-apps cabal.project is configured for 2.0  and this change is more for readability.
[PLT-5442](https://input-output.atlassian.net/browse/PLT-5442)

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Formatting, PNG optimization, etc. are updated
    - [ ] Important changes are reflected in changelog.d of the affected packages
- PR
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reference the ADR in the PR and reference the PR in the ADR (if revelant)
    - [ ] Reviewer requested

[PLT-5442]: https://input-output.atlassian.net/browse/PLT-5442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by kayvank** [comment]
> Shouldn't the aeson lower bound change for _all_ Haskell projects in plutus-apps?

it is already set to >=2 in [cabal.project](https://github.com/input-output-hk/plutus-apps/blob/main/cabal.project#L90)

**Comment by koslambrou** [comment]
@kayvank Ah cool. Can you force-push to re-trigger a CI run.

**Comment by koslambrou** [comment]
@kayvank Can you fix conflicts so that we can merge this?

**Comment by kayvank** [comment]
> @kayvank Can you fix conflicts so that we can merge this?

@koslambrou  they're resolved now, thnx

**Pull request merged**
