### PR TITLE
Switch to using `ImportQualifiedPost`

### PR DESCRIPTION
**Pull request by sjoerdvisscher**
Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

### CODE REVIEW

**Comment by michaelpj** [comment]
You'll also need to bump the `stylish-haskell` version to 0.13.0.0, I think.

**Review by silky — APPROVED** [review]
If CI is happy I'm happy! Thanks for doing this :)

**Comment by silky** [comment]
@sjoerdvisscher a minor issue I failed to notice ... 😂

**Comment by sjoerdvisscher** [comment]
@silky Same here, otherwise I hadn't tagged you to review it yet 😆

**Pull request merged**
