### PR TITLE
[chain-index]: Handle rollback and resume events properly.

### PR DESCRIPTION
**Pull request by ak3n**
Cherry-picked https://github.com/etiennejf/plutus-apps/commit/cd25afa44916483986978e8a8d787227d228f1b1 with some updates:

- replaced `break` with `span` for readability
- moved the logging out of the `processEvents`

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [ ] Formatting, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [ ] Reference the ADR in the PR and reference the PR in the ADR (if revelant)
    - [x] Reviewer requested

### CODE REVIEW

**Comment by koslambrou** [comment]
LGTM. Seems to correctly handle all the events. 
CC @etiennejf

**Review by raduom — APPROVED** [review]
LGTM

**Comment by etiennejf** [comment]
I'm ok with the modifications. Note that I've done a similar thing in our repo but rollback to the previous version due to the fact that chain-index was not progressing at all during syncing. I'm currently performing a full sync on the testnet to see if the problem pops up again.

**Comment by ak3n** [comment]
@etiennejf Thanks for the fix!

>I'm currently performing a full sync on the testnet to see if the problem pops up again.

Yeah, please, let us know if you will get some info on this.

**Comment by etiennejf** [comment]
I'm having a weird behavior on the testnet since the Vasil HF. Here is part of the logs obtained with the current patch.

```
[chain-index:Info:168] [2022-07-06 17:53:22.53 UTC] Syncing (99.60%). Processed 4 blocks, 0 rollbacks in the last 3s. Current tip is Point(Slot 62510369, BlockId d931221f9bc4cae34de422d9f4281a2b0344e86aac6b31eb54e2ee90f44a09b9)
[chain-index:Info:168] [2022-07-06 17:53:22.53 UTC] Syncing (0.00%). Processed 0 blocks, 1 rollbacks in the last 0s. Current tip is PointAtGenesis
[chain-index:Error:168] [2022-07-06 17:53:30.65 UTC] ChainIndexError: Insertion failed: UTxO insertion failed - already a block with the given number
[chain-index:Info:168] [2022-07-06 17:53:32.70 UTC] Syncing (0.05%). Processed 31521 blocks, 0 rollbacks in the last 10s. Current tip is Point(Slot 32549, BlockId 9252fb22d8f6d495e32c\25eed78f10cf42d81c53a17594c510dbeccde6c1f0d9)
```
Whenever we will reach a fully sync state, chain-index restarts the syncing all over again. Is there anything to consider in chain-index to be compatible with Vasil HF.

**Comment by manupadillaph** [comment]
Chain index is not syncing in tesnet after Slot 62510369. 
BlockId d931221f9bc4cae34de422d9f4281a2b0344e86aac6b31eb54e2ee90f44a09b9
I download the latest plutus apps and syncing from zero with no success.
Im using with cardano-node-1.35.0-linux which is syncing 100%

**Pull request merged**
