### PR TITLE
RFC: Vendor servant-purescript and purescript-bridge into playground-common

### PR DESCRIPTION
**Pull request by andreabedini**
In the endless quest to get rid of `source-repository-package` stanzas I suggest we vendor servant-purescript and purescript-bridge into playground-common into playground-common.

servant-purescript and purescript-bridge are abbandonware on hackage and have been forked and maintained for IOG by @jhbertra. They are also used by marlowe-playground although there's some attempts to move away from them.

We use `playground-common` in `plutus-use-cases`, `plutus-doc`, `plutus-pab` and `plutus-pab-executables`. 

Before:

```mermaid
graph TD;
    plutus-doc --> playground-common;
    plutus-use-cases --> playground-common;
    plutus-pab --> playground-common;

    plutus-doc --> plutus-use-cases;
    plutus-pab-executables --> plutus-use-cases;

    plutus-pab-executables --> playground-common;
    plutus-pab-executables --> plutus-pab;
   
    plutus-pab-executables --> servant-purescript;

    playground-common --> purescript-bridge;
    playground-common --> servant-purescript;
    plutus-pab-executables --> purescript-bridge;
    servant-purescript --> purescript-bridge;
```

After:

```mermaid
graph TD;
    plutus-doc --> playground-common;
    plutus-use-cases --> playground-common;
    plutus-pab --> playground-common;

    plutus-doc --> plutus-use-cases;
    plutus-pab-executables --> plutus-use-cases;

    plutus-pab-executables --> playground-common;
    plutus-pab-executables --> plutus-pab;
```

Vendoring the packages basically means that consumers of (e.g.) plutus-pab will need to use `Language.PureScript.Bridge`  from `playground-common` and that would be incompatible with the original hackage package. If a plutus-pab consumer is already using purescript-bridge or servant-purescript from hackage (very, very unlikely, given the current situation), they will need to use the modules exposed from `playground-common` to interact with `plutus-pab`. Note that the [package-qualified import syntax](https://downloads.haskell.org/ghc/latest/docs/users_guide/exts/package_qualified_imports.html) allows to disambiguate modules exposed from multiple packages.

This is still compatible with publishing these packages on chap (after we solve the issue with cardano-ledger).

Thoughts @koslambrou @michaelpj ?

### CODE REVIEW

**Comment by andreabedini** [comment]
`hydraJobs.native.checks.plutus-use-cases.plutus-use-cases-test.x86_64-linux` is flaky as it failed in the CI but passes on my machine (tested with `nix build github:input-output-hk/plutus-apps/b7462dc49574d2eca63a959a7707ef902072ee09#hydraJobs.native.checks.plutus-use-cases.plutus-use-cases-test.x86_64-linux`).

I cannot try `hydraJobs.required.x86_64-darwin` as I don't have darwin.

**Comment by andreabedini** [comment]
> I would rather consider removing `playground-common` at all since there is no playground anymore.

We still need it in PAB (as the diagram shows). Would you be able to pick apart what we need from it at the module level?

**Comment by zeme-iohk** [comment]
Seems like the only CI test failing is `marconi-test`, which is odd since we merged https://github.com/input-output-hk/plutus-apps/pull/867 to fix just that. @eyeinsky any idea what could be happening? We're still getting a permission denied https://ci.zw3rk.com/build/979120/nixlog/1

**Comment by eyeinsky** [comment]
#867 was half of the story, the hedgehog-extras PR https://github.com/input-output-hk/hedgehog-extras/pull/18 should be merged (and depended on) too.

**Comment by andreabedini** [comment]
@ak3n suggested we should remove playground-common entirely but parts of plutus-pab still use it. I had a stab a removing it in [this branch](https://github.com/input-output-hk/plutus-apps/tree/remove-playground-common) but I am not sure what to do exactly.

**Comment by michaelpj** [comment]
I would have thought we could remove them? Since these purescript bridges are only used to bridge to purescript frontends, which we don't have, even for the PAB? It might be a bit of work to untangle.

**Comment by andreabedini** [comment]
Closing in favour of https://github.com/input-output-hk/plutus-apps/pull/891

**Pull request closed without merging**
