### PR TITLE
Bump vulnerable dependencies in package.json

### PR DESCRIPTION
**Pull request by zeme-iohk**
As suggested in https://github.com/input-output-hk/plutus-apps/security/dependabot

### CODE REVIEW

**Review by james-iohk — APPROVED** [review]
Thanks @zeme-iohk.  I'm wondering whether we want to keep these tests or only focus on Marconi.

**Comment by zeme-iohk** [comment]
Are these test failures somehow related to the changes in package.json? @james-iohk

**Comment by james-iohk** [comment]
Sorry, what test failures? @zeme-iohk

**Comment by zeme-iohk** [comment]
https://ci.zw3rk.com/eval/26821
They appear to be non-deterministic

**Pull request merged**
