### PR TITLE
PLT-5775: plutus-ledger refactoring

### PR DESCRIPTION
**Pull request by sjoerdvisscher**
So there's no reduction in dependencies at all. I got rid of the direct `plutus-script-utils` dependency from `cardano-node-emulator`, but it is still an indirect dependency through `plutus-ledger`. Maybe if we can get rid of `DecoratedTxOut` in the future we could remove the dependency completely.

Pre-submit checklist:
- Branch
    - [x] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Formatting, PNG optimization, etc. are updated
    - [x] Important changes are reflected in changelog.d of the affected packages
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [ ] Reference the ADR in the PR and reference the PR in the ADR (if revelant)
    - [x] Reviewer requested

### CODE REVIEW

**Comment by berewt** [comment]
All the improvements look good to me but we're far from the story goal (that seems impossible to achieve). I think we can merge this one and we'll decide later on what to do with `plutus-ledger`. @koslambrou does it sound ok for you?

**Comment by koslambrou** [comment]
Fine by me

**Review by berewt — APPROVED** [review]
Let's ship it then!

**Comment by sjoerdvisscher** [comment]
@koslambrou Can you force merge?

**Pull request merged**
