### PR TITLE
add test check utxo function

### PR DESCRIPTION
**Pull request by kk-anlm**
Add a function to check if datum and value matching while testing. Function `dataAtValue` only check with a list of datums, while we want to check if a datum is matching with the right value in testing. For example:
`checkOutputsWithDatumAtAddress @OracleDatum (oracleAddress oracleParams) (== [(Price AssocMap.empty, unitValue oracleToken)])`

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

### CODE REVIEW

**Review by kk-hainq — CHANGES_REQUESTED** [review]
Nice utility but still need better code and documentation. Both `plutus-contract` and `plutus-use-cases` import and use `Plutus.Contract.Test` a lot. This PR would be way more convincing if you could use these functions somewhere there to show its usage, and that it is an upgrade from an old way of writing things, etc. Those diffs would be very helpful.

**Comment by silky** [comment]
@kk-anlm - Thanks for the work so far on this; are you planning to continue on? Otherwise I'll close due to inactivity.

**Comment by kk-anlm** [comment]
> @kk-anlm - Thanks for the work so far on this; are you planning to continue on? Otherwise I'll close due to inactivity.

I'm still working on it. Hope to have comments to finish.

**Comment by kk-anlm** [comment]
We don't follow this direction anymore.

**Pull request closed without merging**
