### PR TITLE
Add haskell-language-server-wrapper to the devshell

### PR DESCRIPTION
**Pull request by zeme-iohk**
VSCode lookups the `haskell-language-server-wrapper` and falls back to `haskell-language-server`.
So if the user has installed `haskell-language-server-wrapper` on their system, VSCode will find and use that instead of 
the `haskell-language-server` provided by the shell

### CODE REVIEW

**Comment by james-iohk** [comment]
I get the same result on `main` and `zeme-iohk/fix-hls` branches.
Screenshot_20230220_114509

**Review by james-iohk — APPROVED** [review]
This now works for me, thanks :+1:

**Review by james-iohk — CHANGES_REQUESTED** [review]
Update CONTRIBUTING.adoc important notice

**Comment by zeme-iohk** [comment]
> Update CONTRIBUTING.adoc important notice

Unsure what you mean

**Comment by james-iohk** [comment]
@zeme-iohk In CONTRIBUTING/adoc it reads
> This binary is called haskell-language-server, rather than haskell-language-server-wrapper, which is what some of the editor integrations expect.

This suggests there is still no `haskell-language-server-wrapper`

**Comment by zeme-iohk** [comment]
Thank you, I've updated it

**Review by james-iohk — APPROVED** [review]

**Review by sjoerdvisscher — APPROVED** [review]

**Pull request merged**
