### PR TITLE
Add inline datum functionality for state machines

### PR DESCRIPTION
**Pull request by jonathanfishbein1**
Pre-submit checklist:
- Branch
    - [x] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Formatting, PNG optimization, etc. are updated
    - [ ] Important changes are reflected in changelog.d of the affected packages
- PR
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reference the ADR in the PR and reference the PR in the ADR (if revelant)
    - [ ] Reviewer requested

### CODE REVIEW

**Review by berewt — CHANGES_REQUESTED** [review]
Thanks for the submission! I still need to investigate the golden tests issues, as I don't understand yet how the changes impact the script address. Some minor refactoring can also improve the readability and ease the maintenance.
I asked also a review from @sjoerdvisscher who is more knowledgeable of this part of the codebase.
(while we're investigating the golden value mismatches, you can already run `cabal test --test-option=--accept` in `plutus-use-cases` and commit the changes to add the new outputs to the PR.)

**Comment by sjoerdvisscher** [comment]
It makes sense that the golden tests fail, since this changes on-chain scripts.

After you make the changes @berewt suggests I'll do a final review, but this looks good overal!

**Comment by berewt** [comment]
That's why it puzzled me: when the `inline` flag is `False`, i thought we would end with exactly the same constraints and tx as before, and thus to the same script.

**Comment by sjoerdvisscher** [comment]
The `if`-statement that checks for the flag is also in on-chain code.

**Comment by sjoerdvisscher** [comment]
I would be fine with only having the inline datum version.

**Comment by berewt** [comment]
> I would be fine with only having the inline datum version.
It would indeed simplify the code and avoid this drawback. @jonathanfishbein1 would you be ok to change it accordingly? (it deprecates my review comments)

**Comment by jonathanfishbein1** [comment]
Sure, just want to make sure I understand correctly, you want to replace `mustPayToTheScriptWithDatumInTx` with `mustPayToTheScriptWithInlineDatum` completely thereby making the if expression unnecessary as well as the `smInlineDatum :: Bool` field

**Comment by berewt** [comment]
Yes, that's it. Overall, inlining is better than putting the datum in the tx, and due to the design of the constraint library, providing the choice would kill the potential benefit.

**Comment by jonathanfishbein1** [comment]
ScriptHashes will be different even without the if expression because the constructors below are different

```{-# INLINABLE mustPayToTheScriptWithDatumInTx #-}
mustPayToTheScriptWithDatumInTx :: o -> Value -> TxConstraints i o
mustPayToTheScriptWithDatumInTx dt vl =
    mempty { txOwnOutputs = [ScriptOutputConstraint (TxOutDatumInTx dt) vl Nothing] }

{-# INLINABLE mustPayToTheScriptWithInlineDatum #-}
mustPayToTheScriptWithInlineDatum :: o -> Value -> TxConstraints i o
mustPayToTheScriptWithInlineDatum dt vl =
    mempty { txOwnOutputs = [ScriptOutputConstraint (TxOutDatumInline dt) vl Nothing] }
```

**Comment by sjoerdvisscher** [comment]
Yes, but it’s not a problem that they are different!

**Comment by berewt** [comment]
Yes we solved this misunderstanding on discord. Jonathan has opened a new PR, unfortunately, our CI doesn't want to forward its answer, gonna link to it in the PR.

**Pull request closed without merging**
