### PR TITLE
Fix computeRefinedCoverageIndex resulting in extra coverage annotations

### PR DESCRIPTION
**Pull request by MaximilianAlgehed**
This PR introduces a hack to get around the issue whereby `computeRefinedCoverageIndex` introduces spurious unreachable coverage annotations.

### CODE REVIEW

**Comment by MaximilianAlgehed** [comment]
@koslambrou Do you know what's wrong here and how to fix it? I can't access the output of CI...

**Comment by berewt** [comment]
> @koslambrou Do you know what's wrong here and how to fix it? I can't access the output of CI...

It's a failing golden test: `renders a game guess scenario sensibly`, from `Spec.Rollup`.

**Comment by MaximilianAlgehed** [comment]
Right, that golden test needs to be updated now that the coverage annotation has been removed...

**Comment by koslambrou** [comment]
@MaximilianAlgehed We're undergoing CI changes again... I'll let you know once everything is back in a stable state.

**Comment by koslambrou** [comment]
@MaximilianAlgehed CI should be working now.

**Comment by koslambrou** [comment]
@MaximilianAlgehed It won't run right now because you have conflicts

**Comment by MaximilianAlgehed** [comment]
@koslambrou how do I run ci locally? I can't see what's going on in CI.

**Comment by koslambrou** [comment]
@MaximilianAlgehed Only the darwin build fails, and it is not required. The linux build passes, so we can merge this PR

**Review by koslambrou — APPROVED** [review]

**Comment by MaximilianAlgehed** [comment]
@koslambrou can we push the merge button here?

**Comment by MaximilianAlgehed** [comment]
@koslambrou what do we need to do to get this merged?

**Comment by koslambrou** [comment]
Thanks for the reminder!

**Pull request merged**
