### PR TITLE
Contractmodel split

### PR DESCRIPTION
**Pull request by MaximilianAlgehed**
This is a duplication of #844 for CI purposes.

### CODE REVIEW

**Comment by MaximilianAlgehed** [comment]
I don't know what's going on but I'm hitting this wonderful error when doing `cabal build all`. I wasn't expecting `cardano-node` to fail to build??
```
src/Cardano/Node/Tracing/Documentation.hs:199:17: error:
    • Couldn't match type ‘Text’ with ‘Char’
        arising from the literal ‘"Resources"’
    • In the fourth argument of ‘mkCardanoTracer’, namely ‘"Resources"’
      In a stmt of a 'do' block:
        resourcesTr <- mkCardanoTracer
                         trBase trForward mbTrEKG "Resources" (const []) (const Info)
                         allPublic
      In the expression:
        do trConfig <- readConfiguration configFileName
           let trBase :: Trace IO FormattedMessage
                 = docTracer (Stdout MachineFormat)
               trForward :: Trace IO FormattedMessage = docTracer Forwarder
               ....
           nodeInfoTr <- mkDataPointTracer trDataPoint (const ["NodeInfo"])
           configureTracers trConfig docNodeInfoTraceEvent [nodeInfoTr]
           ....
    |
199 |                 "Resources"
    |                 ^^^^^^^^^^^

<no location info>: warning: [-Wunused-packages]
    The following packages were specified via -package or -package-id flags,
    but were not needed for compilation:
      - tracer-transformers-0.1.0.1
      - safe-exceptions-0.1.7.3
      - lobemo-backend-trace-forwarder-0.1.0.0
      - lobemo-backend-monitoring-0.1.0.0
      - lobemo-backend-ekg-0.1.0.1
      - lobemo-backend-aggregation-0.1.0.0
      - ekg-core-0.1.1.7
      - ekg-0.4.0.15
cabal: Failed to build cardano-node-1.35.3 (which is required by
```
@zeme-iohk any thoughts?

**Comment by berewt** [comment]
That's a new one indeed. I'll try to reproduce it tomorrow.

**Comment by berewt** [comment]
I wasn't able to reproduce the `cardano-node` bug (I was stuck with a missing `Generic` instance in the `Escrow` tutorial).

**Comment by MaximilianAlgehed** [comment]
@berewt I think I've fixed the remaining issues now. Please verify when CI returns :)

**Review by berewt — APPROVED** [review]
Can be merged as soon as the CI wakes up from the darkness.

**Comment by berewt** [comment]
No, unfortunately, the CI failure is on our side, we even try to submit the branch again in another PR without any success. And no one on board this week has the right to force the merge.
I'm following the issue though and I'll ping you if you need to do anything on your side.

**Comment by berewt** [comment]
Replaced by #889.

**Pull request closed without merging**
