### PR TITLE
Move playground schema to plutus-pab-schema

### LINKED ISSUE #212: Remove mandatory playground and PureScript dependencies from PAB
### Describe the feature you'd like

Many (if not most?) PAB users do not care about the playground nor use PureScript in their projects (also see #19). However, the current setup forces them to build and track `playground-common`, the `purescript-bridge` & `servant-purescript` forks, and more related dependencies by default. This is unnecessarily resource-consuming and scary. It would be way better if `plutus-pab` doesn't depend on any playground and PureScript machinery by default.

From a quick experiment, it looks like `plutus-pab` only needs `FunctionSchema`, `FormSchema`, and perhaps `EndpointToSchema` from `playground-common`, which may be ported to `plutus-schema` or something? For PureScript we can just port `Plutus.PAB.Run.PSGenerator` to `plutus-purescript`? 

We would love to work on this if accepted.

### Describe alternatives you've considered

We can progress just fine with these dependencies in place. However, we do believe PAB would be a lot more user-friendly without them. This will also ease off dependency management a bit for dApp developers, which at the moment is quite stressful and unfriendly, see #180.

### PR DESCRIPTION
**Pull request by ak3n**
an attempt to fix #212 (second half)

TODO:

- allow to integrate schema's `apiHandler`
- client

---

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

### CODE REVIEW

**Comment by koslambrou** [comment]
Is there something blocking this PR?

**Comment by ak3n** [comment]
I got stuck on something related to Servant API and server type mismatch.

I'm not sure I like the solution that I got in this PR. It makes the PAB more modular but also more complex. Too modular to my taste. We don't have a need in such complexity yet.

It raises the question what's the point of `/schema` endpoint? I haven't found any usage in the PAB itself. I suspect that the only client of it might be Marlowe. Then maybe we should move that functionality there? I don't know if usual PAB users need contract schemas. Would love to hear your opinion.

**Comment by kk-hainq** [comment]
> It raises the question what's the point of /schema endpoint? I haven't found any usage in the PAB itself. I suspect that the only client of it might be Marlowe. Then maybe we should move that functionality there? I don't know if usual PAB users need contract schemas. Would love to hear your opinion.

True...

@koslambrou @ak3n Can we nuke it here, and re-add to Marlowe later on if such a demand arises?

**Comment by ak3n** [comment]
@kk-hainq we have discussed it internally and I will try again to take a look and if it won't be possible to re-organize the dependencies then we will remove the `/schema` endpoint completely.

**Pull request closed without merging**
