### PR TITLE
Move to `quickcheck-dynamic` version 3

### PR DESCRIPTION
**Pull request by MaximilianAlgehed**
This requires updating the index state, which is not exactly smooth sailing! I'm pretty sure what I have here won't build, but I'd like some input from @zeme-iohk and @koslambrou.

Pre-submit checklist:
- Branch
    - [x] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Formatting, PNG optimization, etc. are updated
    - [x] Important changes are reflected in changelog.d of the affected packages
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reference the ADR in the PR and reference the PR in the ADR (if revelant)
    - [x] Reviewer requested

### CODE REVIEW

**Comment by koslambrou** [comment]
The error in the pre-commit check basically tells you to update the `hackage.nix` as the index-state you provided is not known.

I'll try to update the `hackage.nix` in a different PR.

**Comment by koslambrou** [comment]
If you haven't seen it, you have this error:

```
game state machine crash tolerance:                                            FAIL (0.71s)
      *** Failed! (after 8 tests):
      Exception while generating shrink-list:
        QuickCheck.elements used with empty list
        CallStack (from HasCallStack):
          error, called at src/Test/QuickCheck/Gen.hs:296:15 in QuickCheck-2.14.2-CiqSnv7rj43Gz4SBHtq619:Test.QuickCheck.Gen
      Exception thrown while showing test case:
        QuickCheck.elements used with empty list
        CallStack (from HasCallStack):
          error, called at src/Test/QuickCheck/Gen.hs:296:15 in QuickCheck-2.14.2-CiqSnv7rj43Gz4SBHtq619:Test.QuickCheck.Gen
      
      Use --quickcheck-replay=216253 to reproduce.
      Use -p '/game state machine crash tolerance/' to rerun this test only.
```

**Comment by MaximilianAlgehed** [comment]
Yeah I was alerted to this earlier today. I'm planning to sort it out tomorrow morning.

**Comment by MaximilianAlgehed** [comment]
The failing haddoc appears to be in a dependency no?

**Comment by MaximilianAlgehed** [comment]
@koslambrou I think this should be ready to merge once CI is done.

**Pull request merged**
