### PR TITLE
Enable uniswap tests

### PR DESCRIPTION
**Pull request by MaximilianAlgehed**
Pre-submit checklist:
- Branch
    - [x] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
    - [x] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

### CODE REVIEW

**Comment by MaximilianAlgehed** [comment]
We need to figure out a way to get this test to pass.

**Comment by ThomasArts** [comment]
This PR puts back some tests that were disabled for the wrong reason.
By enabling them again, we expect to see an error in the balancer pop-up again. If there are Hydra errors, then that's also something that may need to be fixed, because we only expect a contract model test to fail, nothing else.

**Comment by sjoerdvisscher** [comment]
This test should be fixed with #419.

**Comment by MaximilianAlgehed** [comment]
Ok good, then we await that PR being merged before we try to figure out what's up with Hydra here.

**Comment by MaximilianAlgehed** [comment]
@sjoerdvisscher this still doesn't appear to be fixed. After fixing some annoying stuff to do with predicting ada on UTxOs in the tests (which you basically can't do...) I still get "value contains less than min ada" failures in the model. The counterexample is:
```
Actions
 [tok1 := Start,
  tok2 := SetupTokens,
  tok4 := CreatePool (Wallet 4) tok2.D 1 tok2.B 1,
  tok31 := CreatePool (Wallet 2) tok2.B 1 tok2.A 1,
  AddLiquidity (Wallet 4) tok2.B 0 tok2.A 3,
  tok64 := CreatePool (Wallet 4) tok2.A 1 tok2.C 1,
  AddLiquidity (Wallet 4) tok2.B 0 tok2.A 5]
Expected funds of W[4] to change by
  SymValue {symValMap = fromList [(tok2.A,999991),(tok2.B,999999),(tok2.C,999999),(tok2.D,999999),(tok4.Liquidity,1),(tok31.Liquidity,2),(tok64.Liquidity,1)], actualValPart = Value (Map [])}
but they changed by
  SymValue {symValMap = fromList [(tok2.A,999996),(tok2.B,999999),(tok2.C,999999),(tok2.D,999999),(tok4.Liquidity,1),(tok31.Liquidity,1),(tok64.Liquidity,1)], actualValPart = Value (Map [])}
a discrepancy of
  SymValue {symValMap = fromList [(tok2.A,5),(tok31.Liquidity,-1)], actualValPart = Value (Map [])}
```

**Comment by MaximilianAlgehed** [comment]
```[INFO] Slot 48: W[4]: Finished balancing:
                        Tx 7d49887431d4152d99dbfcc432f281253ed8242b86f9c3257b213c99c6eee88f:
                          {inputs:
                             - 2303b12237e7d94259ae7cf04b5b21219b021f2cb74b5a10195a6f9b42a6fe60!2

                             - 2303b12237e7d94259ae7cf04b5b21219b021f2cb74b5a10195a6f9b42a6fe60!3

                             - 2303b12237e7d94259ae7cf04b5b21219b021f2cb74b5a10195a6f9b42a6fe60!4

                             - 2fbac364045f0fec8a078ee11b6473366ff0eb6ac89aa33d977dd4ca1faffe0f!0
                               <>
                          collateral inputs:
                            - 2303b12237e7d94259ae7cf04b5b21219b021f2cb74b5a10195a6f9b42a6fe60!3

                          outputs:
                            - Value (Map [(,Map [("",2000000)]),(376c89700370ad6a1d5f11bbd8e6d070b0011ca8e09b67bb7669ff4a,Map [("A",9),("B",1)]),(a6ce5f802f1dadf50dae91880ade7787b2f6280ab14c4f3d33a2c296,Map [("Pool State",1)])]) addressed to
                              ScriptCredential: 4f750774388c4ac004d607ab84a8ab2c81544fd420e1aeb43206fa95 (no staking credential)
                            - Value (Map [(,Map [("",2000000)]),(a6ce5f802f1dadf50dae91880ade7787b2f6280ab14c4f3d33a2c296,Map [(0x57eeed951727bdc5729a319fad803dead5b3b2ec3363d254b66a0fb342555a00,1)])]) addressed to
                              PubKeyCredential: 557d23c0a533b4d295ac2dc14b783a7efc293bc23ede88a6fefd203d (no staking credential)
                            - Value (Map [(,Map [("",99999999965229293)])]) addressed to
                              PubKeyCredential: 557d23c0a533b4d295ac2dc14b783a7efc293bc23ede88a6fefd203d (no staking credential)
                            - Value (Map [(,Map [("",2000000)]),(376c89700370ad6a1d5f11bbd8e6d070b0011ca8e09b67bb7669ff4a,Map [("A",999991),("B",999999),("C",999999),("D",999999)]),(a6ce5f802f1dadf50dae91880ade7787b2f6280ab14c4f3d33a2c296,Map [(0x57eeed9
51727bdc5729a319fad803dead5b3b2ec3363d254b66a0fb342555a00,1),(0x77c201893baaafb0cdec91702749a7370c5c98e9f8b8164505349d3e05ffb444,1),(0x7cb6373701c4ceb558ec4159d079f27d6b998544cf1ba27eb12ab7959ae06680,1)])]) addressed to
                              PubKeyCredential: 557d23c0a533b4d295ac2dc14b783a7efc293bc23ede88a6fefd203d (no staking credential)
                          mint: Value (Map [(a6ce5f802f1dadf50dae91880ade7787b2f6280ab14c4f3d33a2c296,Map [(0x57eeed951727bdc5729a319fad803dead5b3b2ec3363d254b66a0fb342555a00,1)])])
                          fee: Value (Map [(,Map [("",7424514)])])
                          mps:
                            MintingPolicy { <script> }
                          signatures:
                          validity range: Interval {ivFrom = LowerBound NegInf True, ivTo = UpperBound PosInf True}
                          data:
                            <<<<"7l\137p\ETXp\173j\GS_\DC1\187\216\230\208p\176\SOH\FS\168\224\155g\187vi\255J",
                            "B">>,
                            <<"7l\137p\ETXp\173j\GS_\DC1\187\216\230\208p\176\SOH\FS\168\224\155g\187vi\255J",
                            "A">>>,
                            <2>>
                            <<<<"7l\137p\ETXp\173j\GS_\DC1\187\216\230\208p\176\SOH\FS\168\224\155g\187vi\255J",
                            "B">>,
                            <<"7l\137p\ETXp\173j\GS_\DC1\187\216\230\208p\176\SOH\FS\168\224\155g\187vi\255J",
                            "A">>>,
                            <3>>}```

**Comment by MaximilianAlgehed** [comment]
@koslambrou and @sjoerdvisscher any chance we can get eyes on this latest bug in the balancer?

**Comment by sjoerdvisscher** [comment]
One thing I noticed is that it's no longer `prop_Uniswap` that's failing but the `"can create a liquidity pool and add liquidity"` test. So it seems the changes in this PR fix the`prop_Uniswap` test but have broken the other one.

**Comment by MaximilianAlgehed** [comment]
I'm still having it fail but that may be because of the negative testing that we are doing. I'll have a look at it tomorrow and we can see where we are with this.

**Comment by MaximilianAlgehed** [comment]
> One thing I noticed is that it's no longer `prop_Uniswap` that's failing but the `"can create a liquidity pool and add liquidity"` test. So it seems the changes in this PR fix the`prop_Uniswap` test but have broken the other one.

I'm still seeing `prop_Uniswap` fail locally with less than min ada problems.

**Comment by sjoerdvisscher** [comment]
I can reproduce the issue indeed!

Can I easily make a stand-alone testcase from a list of actions like

```
       [tok1 := Start,
        tok2 := SetupTokens,
        tok3 := CreatePool (Wallet 6) tok2.A 1 tok2.B 1,
        tok6 := CreatePool (Wallet 3) tok2.C 1 tok2.D 1,
        tok7 := CreatePool (Wallet 6) tok2.C 1 tok2.B 1,
        AddLiquidity (Wallet 6) tok2.D 0 tok2.C 3,
        AddLiquidity (Wallet 6) tok2.A 0 tok2.B 3]
```

**Comment by MaximilianAlgehed** [comment]
The easiest way I think is to translate it to a dynamic logic test using
the DL monad.

Best regards
*Maximilian Algehed*

**Comment by sjoerdvisscher** [comment]
@MaximilianAlgehed Thanks, that seems like a good idea! I tried this:

```
newTest = do
  action Start
  action SetupTokens
  UniswapModel {_exchangeableTokens = toList -> [a,b,c,d]} <- getContractState
  action $ CreatePool w6 a 1 b 1
  action $ CreatePool w3 c 1 d 1
  action $ CreatePool w6 c 1 b 1
  action $ AddLiquidity w6 d 0 c 3
  action $ AddLiquidity w6 a 0 b 3
```

```
testProperty "newTest" $ withMaxSuccess 1 $ forAllDL newTest propRunActions_
```

but that fails already at the first `CreatePool` action with a validation script failure (phase2 CekEvaluationFailure). What am I doing wrong? Can I not extract the tokens this way?

**Comment by MaximilianAlgehed** [comment]
@sjoerdvisscher that's surprising to me. I've set this up locally and I'm going to see if I can make sense of what's going on there.

**Comment by MaximilianAlgehed** [comment]
Ah, I think I've already figured out what might be wrong: add `(defaultCheckOptionsContractModel & allowBigTransactions)` and use `propRunActionsWithOptions` the way we do in `prop_Uniswap`.

**Comment by MaximilianAlgehed** [comment]
@sjoerdvisscher I've pushed what might be a solution (I haven't had time to compile it yet 😅 )

**Comment by sjoerdvisscher** [comment]
Sorry, I updated my comment but it seems you already read the old one!

**Comment by sjoerdvisscher** [comment]
FYI, in #600 I fixed the minAda issue, but the tests still don't pass (might be a new issue I introduced with #600).

**Comment by MaximilianAlgehed** [comment]
@sjoerdvisscher thanks, I'll rebase on `main` and see what I can do to work this out. It's possible that this is also a separate issue. What failures are you seeing?

**Comment by MaximilianAlgehed** [comment]
This appears to still be a less-than-min-ada issue. Weird.

**Comment by sjoerdvisscher** [comment]
#600 hasn't been merged yet.

**Comment by MaximilianAlgehed** [comment]
Ah... Derp.
Best regards
*Maximilian Algehed*

**Comment by MaximilianAlgehed** [comment]
Both...

**Comment by sjoerdvisscher** [comment]
I was hoping this would work on the new main branch where we now only have ledger validation. But I can't get it to work.

**Pull request closed without merging**
