### PR TITLE
QuickCheck ContractModels that test what happens when a contract crashes

### PR DESCRIPTION
**Pull request by MaximilianAlgehed**
This PR introduces a simple interface for extending a QuickCheck ContractModel of a plutus contract with tests for what happens when offchain code is started and stopped dynamically.

* We split the `[...].ContractModel` module into `[...].ContractModel` (that exposes the unprivileged interface that guarantees whatever invariants are necessary to get sensible tests) and `[...].ContractModel.Internal` (that exposes the internals).
* In the `ContractModel` class we add handles for what contract instances are when we begin testing and what actions start what contract instances.
* We add a module `[...].ContractModel.CrashTolerance` with a class `CrashTolerance` that lets you specify how a contract reacts to offchain code being interrupted.
* We add crash tolerance tests to `GameStateMachine` to show that it does indeed deal with crashing offchain code just fine.

Pre-submit checklist:
- Branch
    - [x] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
    - [x] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

### CODE REVIEW

**Comment by MaximilianAlgehed** [comment]
@sjoerdvisscher I get a very strange error from the tutorial build system here:
```
Warning, treated as error:
/build/source/plutus/tutorials/contract-testing.rst:1197:hs:hsobj reference target not found: Plutus.Contract.Test.ContractModel.chooseQ
```
But as far as I can tell `chooseQ` *is* exported from `Plutus.Contract.Test.ContractModel`. Do you know what's wrong here?

**Comment by sjoerdvisscher** [comment]
I get a number of errors if I do `cabal build plutus-doc`. Does that work for you?

**Comment by MaximilianAlgehed** [comment]
I get zero errors when running `cabal build plutus-doc` in a nix-shell.

**Comment by sjoerdvisscher** [comment]
I can at least reproduce the error with `nix build -f ci.nix darwin.docs.site -L` (use `nix build -f ci.nix linux.docs.site -L` if on linux).

**Comment by sjoerdvisscher** [comment]
I can fix it by replacing `Plutus.Contract.Test.ContractModel` with `Test.QuickCheck.DynamicLogic.Quantify` for `chooseQ` and `Quantification`. Apparently that how hsobj references work when you export a whole module?

**Comment by MaximilianAlgehed** [comment]
Ok, yes that appears to work for me too. However, this is a bit of an unfortunate work-around and I don't understand why this is necessary now when, as far as I can tell, `main` is doing the same thing that we do here without these issues.

**Comment by sjoerdvisscher** [comment]
I think it is because these hsobj references generate links to haddock documentation. And at `Plutus.Contract.Test.ContractModel` haddock only generates a `module Test.QuickCheck.DynamicLogic.Quantify` line and nothing more, so there's nothing there to link to.

**Comment by MaximilianAlgehed** [comment]
But how come it works on `main`? (Does it work on `main`?)

**Comment by sjoerdvisscher** [comment]
I think the test that is now failing has recently been added to CI.

**Comment by sjoerdvisscher** [comment]
@MaximilianAlgehed I fixed it on main, merging in main hopefully makes this pr green.

**Comment by MaximilianAlgehed** [comment]
@sjoerdvisscher I don't know what's up with the CI reporting - just buggy I suspect - but I think this is more or less ready for review now.

**Comment by MaximilianAlgehed** [comment]
Hydra seems to be completely borked...

**Comment by silky** [comment]
Thanks for your efforts here @MaximilianAlgehed - Closing this as stale; but please do re-open if you find the time to fix the build issues!

**Comment by sjoerdvisscher** [comment]
Actually if you open hydra it shows that the build issues are already fixed! It just somehow does not show up here properly. @silky do you have the magic spell to override the checks? ✨

**Pull request merged**
