### PR TITLE
Update cardano-node to 1.35.3-rc1 with deps

### PR DESCRIPTION
**Pull request by ak3n**
Also updates plutus and cardano-ledger.

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [ ] Formatting, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [ ] Reference the ADR in the PR and reference the PR in the ADR (if revelant)
    - [ ] Reviewer requested

### CODE REVIEW

**Comment by koslambrou** [comment]
Yay! Thanks @ak3n

**Review by koslambrou — APPROVED** [review]

**Comment by zmrocze** [comment]
Does this build already? 
It doesn't, right? what node version could I use to compile plutus-apps succesfully? 

getting: 
```
src/Cardano/Api/Gen.hs:999:3: error:
    • Couldn't match type ‘Maybe Lovelace -> ProtocolParameters’
                     with ‘ProtocolParameters’
      Expected type: Gen ProtocolParameters
        Actual type: Gen (Maybe Lovelace -> ProtocolParameters)
    • In the expression:
        ProtocolParameters <$> ((,) <$> genNat <*> genNat)
          <*> (Just <$> genRational)
          <*> liftArbitrary genPraosNonce
          <*> genNat
          <*> genNat
          <*> genNat
          <*> genNat
          <*> genNat
          <*> liftArbitrary genLovelace
          <*> genLovelace
          <*> genLovelace
          <*> genLovelace
          <*> genEpochNo
          <*> genNat
          <*> genRationalInt64
          <*> genRational
          <*> genRational
          <*> liftArbitrary genLovelace
          <*> genCostModels
          <*> liftArbitrary genExecutionUnitPrices
          <*> liftArbitrary genExecutionUnits
          <*> liftArbitrary genExecutionUnits
          <*> liftArbitrary genNat
          <*> liftArbitrary genNat
          <*> liftArbitrary genNat
      In an equation for ‘genProtocolParameters’:
          genProtocolParameters
            = ProtocolParameters <$> ((,) <$> genNat <*> genNat)
                <*> (Just <$> genRational)
                <*> liftArbitrary genPraosNonce
                <*> genNat
                <*> genNat
                <*> genNat
                <*> genNat
                <*> genNat
                <*> liftArbitrary genLovelace
                <*> genLovelace
                <*> genLovelace
                <*> genLovelace
                <*> genEpochNo
                <*> genNat
                <*> genRationalInt64
                <*> genRational
                <*> genRational
                <*> liftArbitrary genLovelace
                <*> genCostModels
                <*> liftArbitrary genExecutionUnitPrices
                <*> liftArbitrary genExecutionUnits
                <*> liftArbitrary genExecutionUnits
                <*> liftArbitrary genNat
                <*> liftArbitrary genNat
                <*> liftArbitrary genNat
    |
999 |   ProtocolParameters
    |   ^^^^^^^^^^^^^^^^^^...

src/Cardano/Api/Gen.hs:1028:3: error:
    • Couldn't match type ‘Maybe Lovelace -> ProtocolParameters’
                     with ‘ProtocolParameters’
      Expected type: Gen ProtocolParameters
        Actual type: Gen (Maybe Lovelace -> ProtocolParameters)
    • In the expression:
        ProtocolParameters <$> ((,) <$> genNat <*> genNat)
          <*> (Just <$> genRational)
          <*> liftArbitrary genPraosNonce
          <*> genNat
          <*> genNat
          <*> genNat
          <*> genNat
          <*> genNat
          <*> liftArbitrary genLovelace
          <*> genLovelace
          <*> genLovelace
          <*> genLovelace
          <*> genEpochNo
          <*> genNat
          <*> genRationalInt64
          <*> genRational
          <*> genRational
          <*> (Just <$> genLovelace)
          <*> genCostModels
          <*> (Just <$> genExecutionUnitPrices)
          <*> (Just <$> genExecutionUnits)
          <*> (Just <$> genExecutionUnits)
          <*> (Just <$> genNat)
          <*> (Just <$> genNat)
          <*> (Just <$> genNat)
      In an equation for ‘genProtocolParametersWithAlonzoScripts’:
          genProtocolParametersWithAlonzoScripts
            = ProtocolParameters <$> ((,) <$> genNat <*> genNat)
                <*> (Just <$> genRational)
                <*> liftArbitrary genPraosNonce
                <*> genNat
                <*> genNat
                <*> genNat
                <*> genNat
                <*> genNat
                <*> liftArbitrary genLovelace
                <*> genLovelace
                <*> genLovelace
                <*> genLovelace
                <*> genEpochNo
                <*> genNat
                <*> genRationalInt64
                <*> genRational
                <*> genRational
                <*> (Just <$> genLovelace)
                <*> genCostModels
                <*> (Just <$> genExecutionUnitPrices)
                <*> (Just <$> genExecutionUnits)
                <*> (Just <$> genExecutionUnits)
                <*> (Just <$> genNat)
                <*> (Just <$> genNat)
                <*> (Just <$> genNat)
     |
1028 |   ProtocolParameters
     |   ^^^^^^^^^^^^^^^^^^...
cabal: Failed to build cardano-testnet-1.35.3 (which is required by
test:plutus-example-test from plutus-example-1.0.0). See the build log above
for details.
Failed to build cardano-wallet-core-2022.7.1 (which is required by
exe:tx-inject from plutus-pab-executables-1.0.0.0, exe:plutus-uniswap from
plutus-pab-executables-1.0.0.0 and others). See the build log above for
details.
```
don't know why 1.35.3 builds, I'm in nix-shell.

**Comment by koslambrou** [comment]
Weird. Try removing `dist-newstyle`?

**Comment by koslambrou** [comment]
@zmrocze You're right. We didn't use the correct hash for the node tag `1.35.3-rc1`. This is being updated in https://github.com/input-output-hk/plutus-apps/pull/657

**Pull request merged**
