### PR TITLE
Chain Index: separate scripts and redeemers tables

### LINKED ISSUE #70: Chain Index: Store scripts and redeemers separately
## Area
[x] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries

## Describe the feature you'd like

Why are redeemers stored together with scripts? For our security work, we want to track all scripts hence all rows in the script table. At the moment, we have to get a row and deserialize it as a `Script` to tell if it is a script or redeemer. Therefore, we have to fetch and check all scripts and redeemers when we experiment with a new transpiler or something. The redeemers are simply dropped in that scenario. On the other hand, we care about redeemers but barely need scripts for dApp integration. Our suggestion is to have two separate tables for them.

They are already separated in `DiskState`:
https://github.com/input-output-hk/plutus-apps/blob/56fc3fa79781ab461020264f0cf00cb667e86f79/plutus-chain-index/src/Plutus/ChainIndex/Emulator/DiskState.hs#L121-L131

The confusion is even more apparent when the current `diagnostics` endpoint also counts redeemers for scripts.
https://github.com/input-output-hk/plutus-apps/blob/942bd8c6de6a2d5981d91c704b0258bddd9d9d7c/plutus-chain-index/src/Plutus/ChainIndex/Handlers.hs#L422

## Describe alternatives you've considered

We have to fetch and deserialize the whole table to tell what is a script and what is a redeemer. 

## Additional context / screenshots

This issue is part of the #4 mega-thread.

### PR DESCRIPTION
**Pull request by kk-hainq**
This PR attempts to resolve #70. I set this as a draft for further testing. I really feel like missing something and no failed tests make it even more worrying.

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
    - [x] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [ ] Reviewer requested

### CODE REVIEW

**Comment by silky** [comment]
Seems reasonable to me; mark it as a non-draft and we'll take a look! Thanks! :)

**Review by sjoerdvisscher — APPROVED** [review]
💯 This makes total sense!

**Comment by kk-hainq** [comment]
@silky @sjoerdvisscher I could confirm that this works fine locally now. I wonder if we should add a test or two?

**Comment by sjoerdvisscher** [comment]
No that's ok, thanks!

**Pull request merged**
