### PR TITLE
ContractModel: Detect Double Satisfaction Problems

### PR DESCRIPTION
**Pull request by MaximilianAlgehed**
This PR introduces a new property to check for double satisfaction vulnerabilities in any contract with a `ContractModel`. This property is not complete, but as far as we know it is sound. See the `checkDoubleSatisfaction` property in `Plutus.Contract.Test.ContractModel`.

Pre-submit checklist:
- Branch
    - [x] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Formatting, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

### CODE REVIEW

**Comment by MaximilianAlgehed** [comment]
@sjoerdvisscher we didn't touch this code, is something broken on main?

**Comment by MaximilianAlgehed** [comment]
@sjoerdvisscher we didn't touch this code, is something broken on main?

**Comment by locallycompact** [comment]
What is a double satisfaction problem?

**Comment by ThomasArts** [comment]
> What is a double satisfaction problem?

https://plutus.readthedocs.io/en/latest/reference/common-weaknesses/double-satisfaction.html?highlight=double%20satisfication

**Comment by sjoerdvisscher** [comment]
@MaximilianAlgehed Hmm, it looks like a legitimate failure, and I don't see it on other branches. Did you try to run `cabal test plutus-pab-test-full-long-running` locally?

**Comment by MaximilianAlgehed** [comment]
... It's a cached failure?!

**Comment by sjoerdvisscher** [comment]
As far as I can tell it is cached from a previous build of this PR.

**Comment by MaximilianAlgehed** [comment]
@sjoerdvisscher there is a change to `Ledger.Index` here! But that's because the semantics of the old code are, as far as I can tell, wrong! The semantics of the old code is that you always pay the collateral, when the semantics should be that you only pay if phase 2 validation fails, no?

**Comment by sjoerdvisscher** [comment]
> the semantics should be that you only pay if phase 2 validation fails, no?

Yes, that's definitely how it's supposed to work.

**Comment by MaximilianAlgehed** [comment]
Then the fact that this test is broken tells us something. Is something broken in the PAB or is something broken elsewhere?

**Comment by MaximilianAlgehed** [comment]
@sjoerdvisscher I'll make a separate PR with that fix and hopefully that means we can dig into the issue in the PAB separately.

**Comment by MaximilianAlgehed** [comment]
Also, @sjoerdvisscher it would be good if you or someone could just have a look over this to make sure there is nothing absolutely insane going on :)

**Comment by sjoerdvisscher** [comment]
> So then the old version was buggy (because of how do and infix notation interact).

😱

> it would be good if you or someone could just have a look over this to make sure there is nothing absolutely insane going on :)

As a comment in the code says `-- Double satisfaction magic`, and as with any magic it is hard to tell if something insane is going on or not! To be honest this is true for most of the ContractModel code. In can review it for code quality (and this is already quite a task since most PRs are quite big) but I can't review the logic.

Don't forget to rebase on main to get the fix for the OOM CI issue.

**Review by sjoerdvisscher — APPROVED** [review]

**Comment by UlfNorell** [comment]
@sjoerdvisscher: 43b73aca2c changed `runValidation` to no longer compute an updated `UtxoIndex`. What's the best way to compute that now? We need to keep an up-to-date `UtxoIndex` when traversing an emulator trace looking for double satisfaction vulnerabilities.

**Comment by sjoerdvisscher** [comment]
Ah sorry, I keep forgetting that we're not the only ones using these functions. You need something like this:

```haskell
        idx' = case e of
            Just (Index.Phase1, _) -> idx
            Just (Index.Phase2, _) -> Index.insertCollateral txn idx
            Nothing                -> Index.insert txn idx
```

**Comment by UlfNorell** [comment]
Does that mean we should to switch to using `CardanoTx`s instead of the emulator `Tx`? Currently we're expecting to find an emulator `Tx` in `TxnValidate` events, but that will now be a `CardanoTx`?

**Pull request merged**
