### PR TITLE
PLT-910: babbage technical debt

### PR DESCRIPTION
**Pull request by sjoerdvisscher**
It's probably best to review this commit by commit, since the changes are not related.

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Formatting, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [ ] Reference the ADR in the PR and reference the PR in the ADR (if revelant)
    - [x] Reviewer requested

### CODE REVIEW

**Comment by koslambrou** [comment]
I think the only thing I see missing is the name changes of some constraints in `TxConstraints` in order to have them be more consistent.

The ones is spotted are:

```
mustPayToTheScript -> mustPayToTheScriptWithDatumHash
mustPayWithDatumToPubKey -> mustPayWithDatumHashToPubKey
mustPayWithDatumInTxToPubKey -> mustPayToPubKeyWithDatumInTx
mustPayWithInlineDatumToPubKey -> mustPayToPubKeyWithInlineDatum
mustPayWithDatumToPubKeyAddress -> mustPayToPubKeyAddressWithDatumHash
mustPayWithDatumInTxToPubKeyAddress -> mustPayToPubKeyAddressWithDatumInTx
mustPayWithInlineDatumToPubKeyAddress -> mustPayToPubKeyAddressWithInlineDatum
mustPayToOtherScript -> mustPayToOtherScriptWithDatumHash
mustPayToOtherScriptAddress -> mustPayToOtherScriptAddressWithDatumHash
mustPayToAddressWithDatum -> mustPayToAddressWithDatumHash
```

**Comment by sjoerdvisscher** [comment]
@koslambrou Ah, I misread that part of the ticket and wanted to discuss with you, but now it's clear, thanks!

**Comment by sjoerdvisscher** [comment]
@koslambrou Done. Can you do a quick re-review?

**Review by koslambrou — APPROVED** [review]
LGTM

**Pull request merged**
