### PR TITLE
Certification framework

### PR DESCRIPTION
**Pull request by UlfNorell**
Framework for level 1 certification.

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [ ] Reviewer requested

### CODE REVIEW

**Comment by MaximilianAlgehed** [comment]
@sjoerdvisscher do you know what's up with the failing GitHub checks?

**Comment by sjoerdvisscher** [comment]
@MaximilianAlgehed Yes, the macs have been updated causing the builds to fail. https://github.com/input-output-hk/plutus/pull/4497 works around this, so rebasing on main should fix this.

**Comment by MaximilianAlgehed** [comment]
@sjoerdvisscher I rebased on `main` but it appears to still be failing!

**Comment by sjoerdvisscher** [comment]
I think you need to do this thing:
```
*** Please run plutus-playground-generate-purs
*** in plutus-playground-client and
*** pab-nami-demo-generate-purs in
*** plutus-pab-executables/demo/pab-nami/client and and commit changes.
```

**Comment by MaximilianAlgehed** [comment]
Thanks :)

**Comment by sjoerdvisscher** [comment]
I ran the nix build locally and it did report an error:

```
src/Plutus/Contract/Test/Certification.hs:7:1: warning: [-Wunused-imports]
     The import of ‘Plutus.Contract.Test.Coverage’ is redundant
```

Hopefully then everything builds except check-for-updates.

**Comment by sjoerdvisscher** [comment]
I created a PR to your branch with some fixes: https://github.com/Quviq/plutus-apps/pull/3

**Comment by sjoerdvisscher** [comment]
Ok, one more thing to try: could you add `plutus-contract-certification.package.buildable = false;` at line 64 in `haskell.nix`?

**Comment by sjoerdvisscher** [comment]
Finally! The failing plutus-use-case is fixed on main. @koslambrou can you merge this please?

**Comment by MaximilianAlgehed** [comment]
Thanks! I'll have a look at these and try to get this up to speed once I'm
by my computer.

**Pull request merged**
