### PR TITLE
Add `foldLedgerStateEvents`

### PR DESCRIPTION
**Pull request by zliu41**
This will be useful for the script dump job. The scripts and their arguments live in `LedgerEvent`s.

The job is currently in an unmerged branch and has been using [this function](https://github.com/input-output-hk/plutus-apps/blob/11cdbb26b7f3168088378c0d8ec01460b8ef6512/plutus-streaming/src/Plutus/Streaming.hs#L159), which is essentially the same as `foldLedgerStateEvents`.

### CODE REVIEW

**Review by andreabedini — APPROVED** [review]
LGTM. It was a bit silly that we were obtaining ledger events from `applyBlock_` and not passing them along.

**Comment by eyeinsky** [comment]
@andreabedini I'm at fault!

Looks great!

**Review by eyeinsky — APPROVED** [review]

**Comment by andreabedini** [comment]
> @andreabedini I'm at fault!

 I thought I had written that code :joy:

**Comment by eyeinsky** [comment]
> > @andreabedini I'm at fault!
> 
> I thought I had written that code joy

Well, you started it! :p

**Comment by andreabedini** [comment]
> Well, you started it! :p

Then it's my fault! :rofl:

**Comment by zliu41** [comment]
My bad for not merging this sooner!

**Pull request merged**
