### PR TITLE
Update .readthedocs.yml

### PR DESCRIPTION
**Pull request by jonesnoaht**
It would be nice to have PDF and EPUB outputs.

Pre-submit checklist:
- Branch
    - [x] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
    - [x] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [ ] Reviewer requested

### CODE REVIEW

**Comment by silky** [comment]
Thanks @jonesnoaht ! :)

@shlevy - Do you know if more needs to be done here to make these available from the docs sites?

**Comment by shlevy** [comment]
@silky @michaelpj has been managing the docs site.

**Comment by michaelpj** [comment]
Apparently it's already enabled in the RTD settings, although putting it here is clearer. I have no idea where you get them from, though.

image

**Comment by silky** [comment]
Merging then to see what happens.

Thanks @jonesnoaht :) If you are able to confirm that this has achieved what you want, that would be great!

**Pull request merged**
