### PR TITLE
Add a swagger ui page for chain index endpoints

### PR DESCRIPTION
**Pull request by kk-hainq**
This is a step forward for #129.
image

I have two questions:

1. Should we derive `OpenApi.ToSchema` instances with the `newtype` strategy like the following?
https://github.com/input-output-hk/plutus-apps/blob/7333e3c3ae62c955c5db7799dbf1c1f58593325d/plutus-ledger/src/Ledger/Orphans.hs#L89

It is cleaner but will lead to imprecise schemas. For instance, the above `Slot` is returned with `getSlot` in the tip endpoint.
```sh
$ curl -s localhost:9083/tip | jq
{
  "tipBlockId": "fd42a734b285b01d40a90a042a92915c931458c24051e2c7e02de505dcf44ccb",
  "tipSlot": {
    "getSlot": 1714
  },
  "tipBlockNo": 684,
  "tag": "Tip"
}
```

The answer might be the other way around, to derive/write `ToJSON` through the `newtype` strategy more? Most things in `Orphans` are in `plutus` though.

2. It is not so clean responding with a tuple in these endpoints:
https://github.com/input-output-hk/plutus-apps/blob/7333e3c3ae62c955c5db7799dbf1c1f58593325d/plutus-chain-index-core/src/Plutus/ChainIndex/Api.hs#L110-L112

Should we write a dedicated data type for each case, at least for better `Aeson` and `OpenApi` instances?

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
    - [x] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [ ] Reviewer requested

### CODE REVIEW

**Comment by silky** [comment]
Hey @kk-hainq 

Thanks for working on this!

Re: 1) I think it's fine to just use the newtype instances (It's not ideal, but it's what we do elsewhere)

Re: 2) I think a richer type might be nice, I agree.

**Review by silky — APPROVED** [review]
Nice, thanks @kk-hainq ! :) If you're happy with it I'll merge?

**Comment by kk-hainq** [comment]
@silky False alarm! I pushed those initial `IsUtxoResponse` commits to see if I missed any CI checks. I did, have fixed it and completed `IsUtxoResponse` similarly. The PR should be ready now.

image

Should I update and write more to `plutus-chain-index` & `plutus-chain-index-core`'s READMEs next?

**Review by silky — APPROVED** [review]

**Comment by silky** [comment]
Yes, that sounds great! Thanks so much for your work :)

**Pull request merged**
