### PR TITLE
[next-node]: upgrade cardano-node to 1.35.4

### PR DESCRIPTION
**Pull request by ghost**
I have checked the versions that `cardano-node` uses by building it in `cardano-node` repo. That allowed me to match the repo git commits in https://input-output-hk.github.io/cardano-haskell-packages/all-package-versions/index.html for our `cabal.project`. The log is below.

<details>
  <summary>cabal build cardano-node</summary>

```
In order, the following will be built (use -v for more details):
 - io-classes-0.2.0.0 (lib) (requires download & build)
 - Win32-network-0.1.1.0 (lib) (requires download & build)
 - cardano-git-rev-0.1.0.0 (lib) (first run)
 - cardano-crypto-1.1.1 (lib) (requires download & build)
 - cardano-crypto-class-2.0.0.0.1 (lib) (requires download & build)
 - flat-0.4.4.0.0.0.0.2 (lib) (requires download & build)
 - hedgehog-corpus-0.2.0 (lib) (requires download & build)
 - monoidal-synchronisation-0.1.0.1 (lib) (requires download & build)
 - plutus-core-1.0.0.1 (lib:index-envs) (requires download & build)
 - typed-protocols-0.1.0.0 (lib) (requires download & build)
 - strict-stm-0.1.0.0 (lib) (requires download & build)
 - io-sim-0.2.0.0 (lib) (requires download & build)
 - iohk-monitoring-0.1.11.0 (lib) (requires download & build)
 - cardano-crypto-wrapper-1.3.0 (lib) (requires download & build)
 - cardano-data-0.1.0.0 (lib) (requires download & build)
 - cardano-crypto-praos-2.0.0.0.1 (lib) (requires download & build)
 - plutus-core-1.0.0.1 (lib) (requires download & build)
 - typed-protocols-cborg-0.1.0.0 (lib) (requires download & build)
 - network-mux-0.1.0.1 (lib) (requires download & build)
 - lobemo-backend-trace-forwarder-0.1.0.0 (lib) (requires download & build)
 - lobemo-backend-monitoring-0.1.0.0 (lib) (requires download & build)
 - lobemo-backend-ekg-0.1.0.1 (lib) (requires download & build)
 - lobemo-backend-aggregation-0.1.0.0 (lib) (requires download & build)
 - cardano-ledger-byron-0.1.0.0 (lib) (requires download & build)
 - set-algebra-0.1.0.0 (lib) (requires download & build)
 - plutus-tx-1.0.0.0 (lib) (requires download & build)
 - ouroboros-network-testing-0.1.0.1 (lib) (requires download & build)
 - cardano-ledger-core-0.1.0.0 (lib) (requires download & build)
 - plutus-ledger-api-1.0.0.1 (lib) (requires download & build)
 - ouroboros-network-framework-0.1.0.1 (lib) (requires download & build)
 - cardano-ledger-shelley-0.1.0.0 (lib) (requires download & build)
 - trace-forward-0.1.0 (lib) (first run)
 - ouroboros-network-0.1.0.1 (lib) (requires download & build)
 - ekg-forward-0.1.0 (lib) (requires download & build)
 - cardano-ledger-shelley-ma-0.1.0.0 (lib) (requires download & build)
 - ouroboros-consensus-0.1.0.1 (lib) (requires download & build)
 - trace-dispatcher-1.29.0 (lib) (first run)
 - cardano-ledger-alonzo-0.1.0.0 (lib) (requires download & build)
 - ouroboros-consensus-byron-0.1.0.1 (lib) (requires download & build)
 - trace-resources-0.1.0.0 (lib) (first run)
 - cardano-ledger-babbage-0.1.0.0 (lib) (requires download & build)
 - cardano-protocol-tpraos-0.1.0.0 (lib) (requires download & build)
 - ouroboros-consensus-protocol-0.1.0.1 (lib) (requires download & build)
 - ouroboros-consensus-shelley-0.1.0.1 (lib) (requires download & build)
 - ouroboros-consensus-cardano-0.1.0.1 (lib) (requires download & build)
 - cardano-api-1.35.4 (lib) (first run)
 - cardano-node-1.35.4 (lib) (first run)
 - cardano-node-1.35.4 (test:cardano-node-test) (first run)
 - cardano-node-1.35.4 (exe:cardano-node) (first run)
 ```

</details>

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Formatting, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [ ] Reference the ADR in the PR and reference the PR in the ADR (if revelant)
    - [x] Reviewer requested

### CODE REVIEW

**Comment by koslambrou** [comment]
That's because you didn't update the sha256

**Review by kayvank — APPROVED** [review]
LGTM

**Comment by koslambrou** [comment]
@ak3n Did you miss updating cardano-ledger?

**Review by koslambrou — APPROVED** [review]

**Comment by koslambrou** [comment]
@ak3n If everything works, I would just merge this to `main` as per the release policy: anything in `main` must use a released version of the node.

**Pull request merged**
